Repository oracle/netsuite-suitecloud-sdk, pull requests merged in 2020-10, with the labels that each got.

#231 SuiteCloud Unit Testing README.md file edited
  packages/unit-testing/README.md
Labels: documentation

#235 Added VSCode extension description & resources
  packages/vscode-extension/README.md
  packages/vscode-extension/resources/acpMain.png
  packages/vscode-extension/resources/cliForNodejsDemo.gif
  packages/vscode-extension/resources/suitecloudCommandList.png
Labels: documentation

#234 PDPDEVTOOL-3744-Update-3rd-party-libs-for-SuiteCloud-SDK-project-in-G…
  package-lock.json
  package.json
  packages/node-cli/package-lock.json
  packages/node-cli/package.json
  packages/unit-testing/package-lock.json
  packages/unit-testing/package.json
Labels: dependencies

#237 bug/PDPDEVTOOL-3528-VSCODE-The-dependencies-installation-Fails-if-Use…
  packages/vscode-extension/messages.json
  packages/vscode-extension/src/core/sdksetup/SdkServices.ts
  packages/vscode-extension/src/service/TranslationKeys.ts
  packages/vscode-extension/src/util/ExtensionUtil.ts
Labels: bug

#238 bug/PDPDEVTOOL-3604-escape-in-setupaccount
  packages/vscode-extension/messages.json
  packages/vscode-extension/src/commands/ManageAccounts.ts
Labels: bug

#240 feature/PDPDEVTOOL-3757-VSCode-account:setup-improve-output
  packages/vscode-extension/messages.json
  packages/vscode-extension/src/commands/ManageAccounts.ts
Labels: enhancement

#246 localserver-cli-command-update-package-lock-json
  extensions/localserver-cli-command/package-lock.json
Labels: dependencies

#244 bugfix/PDPDEVTOOL-3765-U6-Issue-593237-SDF-Node.js-CLI-Importing-of-a…
  packages/node-cli/messages.json
  packages/node-cli/src/commands/object/import/ImportObjectsAction.js
  packages/node-cli/src/commands/object/import/ImportObjectsInputHandler.js
  packages/node-cli/src/services/TranslationKeys.js
Labels: bug

#247 bug/PDPDEVTOOL-3604-escape-in-setupaccount
  packages/vscode-extension/README.md
  packages/vscode-extension/messages.json
  packages/vscode-extension/src/commands/ManageAccounts.ts
Labels: bug

#251 PDPDEVTOOL-3765-merge-to-release-20.2
  packages/node-cli/messages.json
  packages/node-cli/src/commands/object/import/ImportObjectsAction.js
  packages/node-cli/src/commands/object/import/ImportObjectsInputHandler.js
  packages/node-cli/src/services/TranslationKeys.js
Labels: bug

#252 PDPDEVTOOL-3528-update-message-when-java-is-not-installed
  packages/vscode-extension/messages.json
Labels: bug

#253 PDPDEVTOOL-3744-Update-3rd-party-libs-for-SuiteCloud-SDK-project-in-GitHub
  package-lock.json
  package.json
  packages/node-cli/package-lock.json
  packages/node-cli/package.json
  packages/unit-testing/package-lock.json
  packages/unit-testing/package.json
Labels: dependencies

#254 reduce-limit-for-number-of-scripts-per-import-call
  packages/node-cli/src/commands/object/import/ImportObjectsAction.js
Labels: bug

#255 reduce-limit-for-number-of-scripts-per-import-call
  packages/node-cli/src/commands/object/import/ImportObjectsAction.js
Labels: bug
