Repository oracle/netsuite-suitecloud-sdk, pull requests merged in 2022-10, with the labels that each got.

#629 Update dependency vm2 to version 3.9.11
  package-lock.json
  packages/node-cli/package.json
Labels: dependencies

#630 Update node-cli version to 1.6.2
  package-lock.json
  packages/node-cli/package.json
Labels: bug

#635 Update package-lock.json for publishing (vm2)
  package-lock.json
Labels: OCA Verified

#637 Release/pdpdevtool 4964 changelog changes
  packages/vscode-extension/CHANGELOG.md
Labels: OCA Verified

#639 Merge branch release/22.2 when publishing 1.6.2 version of suitecloud-cli
  package-lock.json
  packages/node-cli/package.json
  packages/vscode-extension/CHANGELOG.md
  packages/vscode-extension/package-lock.json
  packages/vscode-extension/package.json
Labels: OCA Verified

#642 Update vm2 library
  package-lock.json
  packages/node-cli/package.json
  packages/vscode-extension/CHANGELOG.md
Labels: OCA Verified

#643 PDPDEVTOOL-4853: Modify display messages for update file in vsCode
  packages/node-cli/messages.json
  packages/node-cli/src/commands/file/import/ImportFilesAction.js
  packages/node-cli/src/commands/file/import/ImportFilesOutputHandler.js
  packages/node-cli/src/metadata/SdkCommandsMetadata.json
  packages/node-cli/src/metadata/SdkCommandsMetadataPatch.json
  packages/node-cli/src/services/TranslationKeys.js
  packages/vscode-extension/messages.json
  packages/vscode-extension/src/commands/CompareFile.ts
  packages/vscode-extension/src/commands/FileImportCommon.ts
  packages/vscode-extension/src/commands/UpdateFile.ts
  packages/vscode-extension/src/service/TranslationKeys.ts
Labels: OCA Verified

#632 PDPDevtool 4922 - Improve versioning management in SuiteCloud SDK
  packages/node-cli/package.json
  packages/node-cli/src/ApplicationConstants.js
  packages/node-cli/src/CLI.js
  packages/node-cli/src/core/sdksetup/SdkProperties.js
  packages/vscode-extension/src/core/sdksetup/SdkProperties.ts
Labels: OCA Verified
