Repository oracle/netsuite-suitecloud-sdk, pull requests merged in 2022-08, with the labels that each got.

#596 PDPDEVTOOL-4862: Bug fixes for vscode-extension Compare Files
  packages/vscode-extension/messages.json
  packages/vscode-extension/src/commands/CompareFile.ts
  packages/vscode-extension/src/service/TranslationKeys.ts
Labels: bug

#598 PDPDEVTOOL-4881 libraries update
  package-lock.json
  packages/node-cli/package-lock.json
  packages/node-cli/package.json
  packages/unit-testing/package-lock.json
  packages/unit-testing/package.json
  packages/vscode-extension/package-lock.json
  packages/vscode-extension/package.json
Labels: dependencies

#599 Bug Fix for PDPDEVTOOL-4862: enhancement to vscode compare files
  packages/vscode-extension/src/commands/CompareFile.ts
Labels: bug

#601 Feature/pdpdevtool 4908 prepare for 2022.2.0 release
  packages/node-cli/package-lock.json
  packages/node-cli/package.json
  packages/node-cli/src/ApplicationConstants.js
  packages/vscode-extension/package-lock.json
  packages/vscode-extension/package.json
Labels: enhancement

#602 PDPDEVTOOL-4908: rollback node-cli dependency to 1.5.0. Will update i…
  packages/vscode-extension/package.json
Labels: enhancement
