Repository oracle/netsuite-suitecloud-sdk, pull requests merged in 2023-11, with the labels that each got.

#766 Documentation updates according to internal requirements
  README.md
  SECURITY.md
Labels: OCA Verified

#768 Propagating documentation changes from master to dev (https://github.com/oracle/netsuite-suitecloud-sdk/pull/766)
  README.md
  SECURITY.md
Labels: documentation, OCA Verified

#772 PDPDEVTOOL-5374: Propagate command errors from node-cli to vscode-ext…
  packages/vscode-extension/src/commands/BaseAction.ts
Labels: bug, OCA Verified
