Repository oracle/netsuite-suitecloud-sdk, pull requests merged in 2024-07, with the labels that each got.

#813 PDPDEVTOOL-5593: [NSN] vscode - oauth2.0 - re-authorize flow
  packages/vscode-extension/messages.json
  packages/vscode-extension/src/commands/BaseAction.ts
  packages/vscode-extension/src/core/SuiteCloudRunner.ts
  packages/vscode-extension/src/service/TranslationKeys.ts
Labels: enhancement, OCA Verified

#814 SBOM creation
  sbom_generation.yaml
Labels: OCA Verified

#816 PDPDEVTOOL-5714 fix the bug about domain not being shown
  packages/node-cli/src/commands/account/manageauth/ManageAccountOutputHandler.js
  packages/node-cli/src/utils/AccountCredentialsFormatter.js
Labels: OCA Verified

#818 PDPDEVTOOL-5714 Fix domain not shown
  packages/node-cli/src/commands/account/manageauth/ManageAccountInputHandler.js
Labels: OCA Verified

#817 PDPDEVTOOL-5587: [NSN] vscode - oauth2.0 - add the new command authenticate ci
  packages/vscode-extension/messages.json
  packages/vscode-extension/src/commands/SetupAccount.ts
  packages/vscode-extension/src/service/TranslationKeys.ts
Labels: enhancement, OCA Verified

#819 PDPDEVTOOL-5714 fix wrong references to account domain, update AuthLi…
  packages/node-cli/src/commands/account/manageauth/ManageAccountAction.js
  packages/vscode-extension/src/commands/ManageAuth.ts
  packages/vscode-extension/src/types/ActionResult.d.ts
Labels: OCA Verified

#821 node-cli dependencies version bump
  package-lock.json
  packages/node-cli/src/templates/unittest/package.json.template
  packages/unit-testing/package.json
Labels: OCA Verified

#815 feature/PDPDEVTOOL 5712 Add release notes and new versions for 24.2
  README.md
  packages/node-cli/README.md
  packages/node-cli/resources/NetSuite-logo-half-light.png
  packages/node-cli/resources/oracle_netsuite_logo_redblack.png
  packages/unit-testing/README.md
  packages/vscode-extension/CHANGELOG.md
  packages/vscode-extension/README.md
  packages/vscode-extension/package.json
  packages/vscode-extension/resources/NetSuite-logo-half-light.png
  packages/vscode-extension/resources/oracle_netsuite_logo_redblack.png
  resources/NetSuite-logo-half-light.png
  resources/oracle_netsuite_logo_redblack.png
Labels: OCA Verified

#806 Feature/pdpdevtool 5615
  packages/node-cli/src/metadata/NodeCommandsMetadata.json
  packages/node-cli/src/metadata/SdkCommandsMetadata.json
  packages/vscode-extension/messages.json
Labels: OCA Verified

#826 Bug Fixes for PDPDEVTOOL-5587: [NSN] vscode - oauth2.0 - add the new command authenticate ci
  packages/vscode-extension/messages.json
  packages/vscode-extension/src/commands/SetupAccount.ts
  packages/vscode-extension/src/service/TranslationKeys.ts
Labels: bug, OCA Verified

#825 PDPDEVTOOL-5749 bump vscode dependencies, remove glob
  packages/vscode-extension/package-lock.json
  packages/vscode-extension/package.json
  packages/vscode-extension/src/test/suite/extension.test.ts
  packages/vscode-extension/src/test/suite/index.ts
Labels: OCA Verified

#827 feature/pdpdevtool-5587 vscode authenticateci cherry pick to release/24.2
  packages/vscode-extension/messages.json
  packages/vscode-extension/src/commands/SetupAccount.ts
  packages/vscode-extension/src/service/TranslationKeys.ts
Labels: OCA Verified

#829 feature/pdpdevtool 5712 bump major versions
  package-lock.json
  packages/node-cli/package.json
  packages/vscode-extension/package-lock.json
  packages/vscode-extension/package.json
Labels: OCA Verified
