Repository oracle/netsuite-suitecloud-sdk, pull requests merged in 2024-08, with the labels that each got.

#831 Set vscode engine version to ^1.91.1
  packages/vscode-extension/package.json
Labels: dependencies, OCA Verified

#830 Add new logos to readme
  README.md
  packages/node-cli/README.md
  packages/node-cli/resources/netsuite_logo_simplified.png
  packages/node-cli/resources/oracle_netsuite_logo_redblack.png
  packages/uif-types/README.md
  packages/uif-types/logo.png
  packages/uif-types/resources/netsuite_logo_simplified.png
  packages/unit-testing/README.md
  packages/unit-testing/resources/netsuite_logo_simplified.png
  packages/unit-testing/resources/oracle_netsuite_logo_redblack.png
  packages/vscode-extension/README.md
  packages/vscode-extension/package.json
  packages/vscode-extension/resources/extension_icon_dark.png
  packages/vscode-extension/resources/netsuite_logo_simplified.png
  packages/vscode-extension/resources/oracle_netsuite_logo_redblack.png
  packages/vscode-extension/resources/pluginIcon_dark.png
  resources/netsuite_logo_simplified.png
  resources/oracle_netsuite_logo_redblack.png
Labels: OCA Verified

#836 Fixing vscode-extension publishing problems
  packages/vscode-extension/package-lock.json
  packages/vscode-extension/package.json
Labels: bug, OCA Verified
